version: '3.8'

services:
  app:
    restart: always
    container_name: tom-tradingview-webhook
    build: .
    ports:
      - "8787"
    env_file:
      - .env
    environment:
      - TZ=Asia/Taipei
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    environment:
      - TZ=Asia/Taipei